### ISSUE TITLE
Review: Businesses

### ISSUE THREAD

**Issue by david-dickinson** [dball1126/Yap#2]
- [ ] Get information from database and render it for each business
- [ ] Lay out basic structure for future business reviews and AWS photos
- [ ] Start with general index page that links to show pages and later will display results based on search params

**Comment by dball1126** [comment]
Information now renders for each business from the database.  Business show page is nearly complete.  Skeleton for Business Index page is in place but not complete due to the need for the Search MVP to be in place.  AWS photos is now configured and working locally at the very least.  Photos show up in the S3 bucket online and I will  test Heroku shortly.
